# Generated by Django 5.0.1 on 2024-01-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_x_alter_item_y_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='died_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date last died'),
        ),
    ]
