# Generated by Django 4.2.9 on 2024-01-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='active',
        ),
        migrations.AddField(
            model_name='item',
            name='disables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item'),
        ),
    ]
