# Generated by Django 4.2.9 on 2024-01-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_item_active_item_disables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disables',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
