# Generated by Django 4.2.9 on 2024-01-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_item_disables'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lane',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
